name: build

on:
  workflow_dispatch:

jobs:
  build-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: swift build -c release
      - run: ./.build/release/LemonFirst 
