name: build

on:
  workflow_dispatch:

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: swift --version
      # - run: swift build -c release
      # - run: ./.build/release/LemonFirst 
